name: Deploy

on:
  workflow_run:
    workflows:
      - Unit Tests
      - Integration Tests
      - Acceptance Tests
    types: [completed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Publish Controller
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          # Cake uses GitVersion.
          fetch-depth: 0

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Push Docker
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: dotnet run cake.cs -- --target=PushContainerController --configuration=Release